name: HelloWorld
version: 1.2
author: Juanma__
main: me.Juanma__.helloworld.Main
description: Mi primer plugin

commands:
  hello:
   aliases: [hi]
   description: Este es el comando hello!
  rainbow:
   aliases: [rb]
   description: Este comando te manda un texto en colores!
   test:
   aliases: [test]
   description: Abre una GUI en el juego